version: 2

sources:
  - name: tmp_csv
    config:
      enabled: true
    tables:
      - name: cattle_canton
      - name: equids_canton
      - name: goats_canton
      - name: sheep_canton
      - name: dogs_canton
      - name: cats_canton
  - name: lzn
    config:
      enabled: true
    tables:
      - name: cats_breeds
      - name: cats_canton
      - name: cats_map_canton
      - name: cats_map_commune
      - name: cattle-map-commune
      - name: cattle_breeds
      - name: cattle_canton
      - name: cattle_map_canton
      - name: cattle_map_commune
      - name: cattle_popvariations
      - name: cattle_evolbeefiness
      - name: cattle_evolfattissue
      - name: cattle_pyr
      - name: dogs_breeds
      - name: dogs_canton
      - name: dogs_map_canton
      - name: dogs_map_commune
      - name: equids_breeds
      - name: equids_canton
      - name: equids_map_canton
      - name: equids_map_commune
      - name: goats_breeds
      - name: goats_canton
      - name: goats_map_canton
      - name: goats_map_commune
      - name: sheep_breeds
      - name: sheep_canton
      - name: sheep_map_canton
      - name: sheep_map_commune
      - name: admin_units_snapshots_wide
      - name: admin_units_geoshapes_wide
      - name: dim_time
  - name: tierstatistik_csv
    config:
      enabled: true
    tables:
      - name: admin_units_geoshapes
