hello-data:
  auth-server:
    admin-client-id: admin-cli
    client-id: frontend-client
    realm: hellodata-dev
    redirect-url: https://portal.dev.hellodatabedag.ch
    url: https://keycloak.3939864b2db64cd08be4.switzerlandnorth.aksapp.io
  business-context: Business Domain | dev | HelloDATA Development
  contexts:
    - Data Domain | demo | Demo | true
    - Data Domain | showcase | Showcase | true
  cors:
    allowed-origins: https://keycloak.3939864b2db64cd08be4.switzerlandnorth.aksapp.io,https://portal.dev.hellodatabedag.ch,http://localhost:8080
  default-admin:
    email: admin@hellodatabedag.ch
    first-name: HelloDATA
    last-name: Admin
    password: admin
    username: admin@hellodatabedag.ch
  system-properties:
    no-reply-email: hellodata-no-reply@hellodata.ch
  ldap:
    base: dc=example,dc=com
    field-mapping:
      email: mail
      first-name: givenName
      last-name: sn
    password: password
    url: ldap://ldap.forumsys.com:389
    username: cn=read-only-admin,dc=example,dc=com
logging:
  level:
    ch.bedag.dap.hellodata.commons.nats.service: DEBUG
    root: INFO
management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: '*'
nats:
  spring:
    server: nats://hd-dev-infrastructure-nats.az-hellodata-dev.svc.cluster.local:4222
server:
  port: 8080
spring:
  boot:
    admin:
      client:
        instance:
          metadata:
            user.name: user
            user.password: password
          service-host-type: IP
        password: password
        url: http://springBootAdmin-sba-service.az-hellodata-dev.svc.cluster.local
        username: user
  cloud:
    discovery:
      enabled: true
    kubernetes:
      discovery:
        enabled: true
  data:
    redis:
      host: hd-dev-infrastructure-redis-master.az-hellodata-dev.svc.cluster.local
      port: 6379
  datasource:
    url: jdbc:postgresql://hellodata-dev.postgres.database.azure.com:5432/dev_portal
  mail:
    host: hd-dev-infrastructure-mailhog.az-hellodata-dev.svc.cluster.local
    password: null
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
      ssl:
        trust: hd-dev-infrastructure-mailhog.az-hellodata-dev.svc.cluster.local
    username: null