# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build selected Module only (with Maven)

run-name: "Build Module: ${{ inputs.module }}"

on:
  workflow_dispatch:
    inputs:
      module:
        description: 'Module to build'
        required: true
        default: 'hello-data-portal/hello-data-portal-api'
        type: choice
        options:
          # Portal
          - hello-data-portal/hello-data-portal-api
          - hello-data-portal/hello-data-portal-ui
          - hello-data-portal/hello-data-portal-ui-e2e
          # Sidecars
          - hello-data-sidecars/hello-data-sidecar-airflow
          - hello-data-sidecars/hello-data-sidecar-portal
          - hello-data-sidecars/hello-data-sidecar-superset
          - hello-data-sidecars/hello-data-sidecar-dbt-docs
          - hello-data-sidecars/hello-data-sidecar-cloudbeaver
          - hello-data-sidecars/hello-data-sidecar-jupyterhub
          - hello-data-sidecars/hello-data-sidecar-sftpgo
          # Subsystems
          - hello-data-subsystems/hello-data-superset
          - hello-data-subsystems/hello-data-airflow
          - hello-data-subsystems/hello-data-cloudbeaver
          - hello-data-subsystems/hello-data-cloudbeaver-gateway
          - hello-data-subsystems/hello-data-dbt-docs
          - hello-data-subsystems/hello-data-monitoring-storage
          - hello-data-subsystems/hello-data-cleanup-logs
          - hello-data-subsystems/hello-data-jupyterhub-gateway
          # Deployment
          - hello-data-deployment/hello-data-dc-cloudbeaver
          - hello-data-deployment/hello-data-dc-keycloak
          - hello-data-deployment/hello-data-dc-portal
          - hello-data-deployment/hello-data-dc-postgres
          - hello-data-deployment/hello-data-dc-airflow
          - hello-data-deployment/hello-data-dc-superset
          - hello-data-deployment/hello-data-showcase
          # Commons
          - hello-data-commons/hello-data-spring-boot-starter-parent
          - hello-data-commons/hello-data-common
          - hello-data-commons/hello-data-base-model
          - hello-data-commons/hello-data-sidecar-common
          - hello-data-commons/hello-data-metainfo-model
          - hello-data-commons/hello-data-nats-spring
          - hello-data-commons/hello-data-portal-common

jobs:

  build:
    runs-on: ubuntu-latest
    environment:
      name: dockerhub
    permissions:
      contents: read
      packages: write

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GIT_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Module with Maven
        env:
          TESTCONTAINERS_RYUK_DISABLED: true
          TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE: /var/run/docker.sock
          DOCKER_HOST: unix:///var/run/docker.sock
        run: mvn -B -pl ${{ github.event.inputs.module }} -am clean install

      - name: Publish Packages and Docker Images
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: mvn --batch-mode deploy -Pdocker -DskipTests -pl ${{ github.event.inputs.module }}

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    #- name: Update dependency graph
    #  uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
